# The file will build Random Forest Regression and KNN and Neural Network Models.

## a). Random Forest Regression

### 1. Load the data and collect features can be used for prediction

In [1]:
# import needed libraries
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.metrics import r2_score
import statsmodels.api as sm # pip install statsmodels
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error

2023-10-04 16:40:36.629731: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-04 16:40:37.006193: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-04 16:40:37.009059: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-04 16:40:38.637226: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
modelling_data = pd.read_csv('../data/curated/final_data/modelling_data_2023.csv')
modelling_data

,personal_income,pop_density,offence_count,log_school_distance,log_station_distance,log_hospital_distance,log_mall_distance,log_park_distance,log_CBD_distance,num_bedroom,num_bathroom,rental_price
0,72706.625309,965.216952,17.333333,0.640804,2.475412,1.906040,1.239505,1.345502,4.578730,4,2,575.0
1,72706.625309,1746.760558,17.333333,-0.348952,1.681479,1.438925,1.052926,1.716843,4.559835,4,2,560.0
2,72706.625309,965.216952,17.333333,0.095820,2.187960,1.847653,1.673884,1.622239,4.586220,2,2,490.0
3,72706.625309,965.216952,17.333333,-0.393160,2.092679,1.736704,0.793410,1.183953,4.578058,4,2,540.0
4,70490.898811,151.921192,31.000000,0.799813,2.315778,2.017863,1.375422,0.115940,4.602687,4,2,520.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8214,100462.815420,1773.237842,25.000000,-2.228826,0.138021,0.374363,0.344505,1.026702,3.826546,2,1,630.0
8215,100462.815420,1773.237842,25.000000,-1.427862,0.754430,1.122437,0.873918,1.320736,3.823240,4,3,730.0
8216,100462.815420,1773.237842,25.000000,-0.199202,1.034856,1.025788,0.821525,1.484705,3.805227,3,1,450.0
8217,100462.815420,1773.237842,25.000000,-1.237029,0.614537,0.623725,0.746158,1.316399,3.810149,1,1,300.0
8218,100462.815420,1773.237842,25.000000,-1.168365,0.425986,0.910821,0.909697,1.072542,3.831748,1,1,420.0

In [3]:
# collect all features
final_features = modelling_data.columns
features_list = final_features.tolist()
features_list.remove('rental_price')
features_list

['personal_income',
 'pop_density',
 'offence_count',
 'log_school_distance',
 'log_station_distance',
 'log_hospital_distance',
 'log_mall_distance',
 'log_park_distance',
 'log_CBD_distance',
 'num_bedroom',
 'num_bathroom']

###  2. Splite the whole data to train & test data --- and build random forest regression

In [4]:
# split training set and test set
X_train, X_test, y_train, y_test = train_test_split(modelling_data[features_list], modelling_data['rental_price'], test_size = 0.1, random_state=123)

# create random forest model
rf_model = RandomForestRegressor(random_state=123)

# define hyperparameter ranges
param_grid = {
    'n_estimators': [100, 150, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10]
}

# create Grid Search object
grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)

# run a Grid Search to find the best hyperparameter combination
grid_search.fit(X_train, y_train)

# print optimal hyperparameter combinations and performance evaluation
print("Best Hyperparameters: ", grid_search.best_params_)
print("Best Negative Mean Squared Error: ", grid_search.best_score_)

Best Hyperparameters:  {'max_depth': 20, 'min_samples_split': 5, 'n_estimators': 150}
Best Negative Mean Squared Error:  -7750.404347753676

In [5]:
# create random rorest model using optimal hyperparameters
best_n_estimators = grid_search.best_params_['n_estimators']
best_max_depth = grid_search.best_params_['max_depth']
best_min_samples_split = grid_search.best_params_['min_samples_split']

final_rf_model = RandomForestRegressor(n_estimators=best_n_estimators, max_depth=best_max_depth, min_samples_split=best_min_samples_split, random_state=123)

# train the final model
final_rf_model.fit(X_train, y_train)

# make predictions and evaluate the model
y_pred = final_rf_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("MSE: {:.2f}".format(mse))
print("MAE: {:.2f}".format(mae))
print("r2 score: {:.2f}".format(r2))

MSE: 6602.44
MAE: 55.13
r2 score: 0.72

## b). KNN Model

In [6]:
# split training set and test set
X_train, X_test, y_train, y_test = train_test_split(modelling_data[features_list], modelling_data['rental_price'], test_size = 0.1, random_state=123)

# scale the data with features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# try different K values, to find the best k with lowest mse
best_mse = float('inf')
best_k = None
for k in range(1, 21):
    knn = KNeighborsRegressor(n_neighbors=k, weights='distance', p=2, metric='minkowski')
    knn.fit(X_train_scaled, y_train)
    y_pred = knn.predict(X_test_scaled)
    mse = mean_squared_error(y_test, y_pred)
    if mse < best_mse:
        best_mse = mse
        best_k = k
print('Best K value is: {:.2f}'.format(best_k))

# train KNN model
best_knn = KNeighborsRegressor(n_neighbors=best_k, weights='distance', p=2, metric='minkowski')
best_knn.fit(X_train_scaled, y_train)

# make predictions and evaluate the model
y_pred = best_knn.predict(X_test_scaled)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("MSE: {:.2f}".format(mse))
print("MAE: {:.2f}".format(mae))
print("r2 score: {:.2f}".format(r2))

Best K value is: 12.00
MSE: 8391.34
MAE: 61.30
r2 score: 0.65

## c). Neural Network Model

In [7]:
# create a sequential model
model = keras.Sequential()

# add input layer, hidden layer, add output layer
model.add(layers.Input(shape=(11,)))  # 11 is the num of features

model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(32, activation='relu'))

model.add(layers.Dense(1))

# build and train the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae', 'mse'])
model.summary()
history = model.fit(X_train_scaled, y_train, epochs=100, validation_split=0.2, verbose=2)

# # make predictions and evaluate the model
y_pred = model.predict(X_test_scaled)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("MSE: {:.2f}".format(mse))
print("MAE: {:.2f}".format(mae))
print("r2 score: {:.2f}".format(r2))

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                768

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2881 (11.25 KB)
Trainable params: 2881 (11.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/100

2023-10-04 16:43:14.841417: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-10-04 16:43:14.841909: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...

185/185 - 1s - loss: 294786.4375 - mae: 518.6917 - mse: 294786.4375 - val_loss: 211691.2188 - val_mae: 432.8056 - val_mse: 211691.2188 - 1s/epoch - 6ms/step
Epoch 2/100
185/185 - 0s - loss: 112453.3828 - mae: 284.0973 - mse: 112453.3828 - val_loss: 53928.4922 - val_mae: 186.9625 - val_mse: 53928.4922 - 326ms/epoch - 2ms/step
Epoch 3/100
185/185 - 0s - loss: 45321.0000 - mae: 166.3099 - mse: 45321.0000 - val_loss: 35877.6484 - val_mae: 146.9787 - val_mse: 35877.6484 - 318ms/epoch - 2ms/step
Epoch 4/100
185/185 - 0s - loss: 33902.1406 - mae: 138.0413 - mse: 33902.1406 - val_loss: 28369.3594 - val_mae: 127.8025 - val_mse: 28369.3594 - 344ms/epoch - 2ms/step
Epoch 5/100
185/185 - 0s - loss: 28385.4004 - mae: 122.8318 - mse: 28385.4004 - val_loss: 24268.3047 - val_mae: 117.1023 - val_mse: 24268.3047 - 316ms/epoch - 2ms/step
Epoch 6/100
185/185 - 0s - loss: 25058.6660 - mae: 113.8319 - mse: 25058.6660 - val_loss: 21741.1953 - val_mae: 110.3381 - val_mse: 21741.1953 - 320ms/epoch - 2ms/step
Epoch 7/100
185/185 - 0s - loss: 22755.1309 - mae: 107.6746 - mse: 22755.1309 - val_loss: 20055.9785 - val_mae: 104.9595 - val_mse: 20055.9785 - 318ms/epoch - 2ms/step
Epoch 8/100
185/185 - 0s - loss: 20996.6699 - mae: 103.0286 - mse: 20996.6699 - val_loss: 18592.1523 - val_mae: 100.5849 - val_mse: 18592.1523 - 368ms/epoch - 2ms/step
Epoch 9/100
185/185 - 0s - loss: 19579.7754 - mae: 99.1540 - mse: 19579.7754 - val_loss: 17458.8398 - val_mae: 97.1464 - val_mse: 17458.8398 - 320ms/epoch - 2ms/step
Epoch 10/100
185/185 - 0s - loss: 18337.3945 - mae: 95.9691 - mse: 18337.3945 - val_loss: 16488.7363 - val_mae: 94.4088 - val_mse: 16488.7363 - 316ms/epoch - 2ms/step
Epoch 11/100
185/185 - 0s - loss: 17414.7422 - mae: 93.4126 - mse: 17414.7422 - val_loss: 15757.4404 - val_mae: 92.2721 - val_mse: 15757.4404 - 318ms/epoch - 2ms/step
Epoch 12/100
185/185 - 0s - loss: 16621.1113 - mae: 91.3759 - mse: 16621.1113 - val_loss: 15178.4639 - val_mae: 90.1243 - val_mse: 15178.4639 - 346ms/epoch - 2ms/step
Epoch 13/100
185/185 - 0s - loss: 16030.3857 - mae: 89.7904 - mse: 16030.3857 - val_loss: 14703.6348 - val_mae: 89.3013 - val_mse: 14703.6348 - 324ms/epoch - 2ms/step
Epoch 14/100
185/185 - 0s - loss: 15530.8232 - mae: 88.5695 - mse: 15530.8232 - val_loss: 14468.3877 - val_mae: 87.7816 - val_mse: 14468.3877 - 312ms/epoch - 2ms/step
Epoch 15/100
185/185 - 0s - loss: 15174.5049 - mae: 87.6218 - mse: 15174.5049 - val_loss: 14016.6094 - val_mae: 86.4897 - val_mse: 14016.6094 - 316ms/epoch - 2ms/step
Epoch 16/100
185/185 - 0s - loss: 14851.4385 - mae: 86.6802 - mse: 14851.4385 - val_loss: 13942.7852 - val_mae: 86.0556 - val_mse: 13942.7852 - 326ms/epoch - 2ms/step
Epoch 17/100
185/185 - 0s - loss: 14560.4707 - mae: 85.8569 - mse: 14560.4707 - val_loss: 13681.8174 - val_mae: 84.6341 - val_mse: 13681.8174 - 320ms/epoch - 2ms/step
Epoch 18/100
185/185 - 0s - loss: 14357.9570 - mae: 85.3185 - mse: 14357.9570 - val_loss: 13486.1064 - val_mae: 84.7168 - val_mse: 13486.1064 - 330ms/epoch - 2ms/step
Epoch 19/100
185/185 - 0s - loss: 14129.3193 - mae: 84.9414 - mse: 14129.3193 - val_loss: 13305.0596 - val_mae: 83.7463 - val_mse: 13305.0596 - 335ms/epoch - 2ms/step
Epoch 20/100
185/185 - 0s - loss: 13941.9717 - mae: 84.0971 - mse: 13941.9717 - val_loss: 13157.7734 - val_mae: 84.3678 - val_mse: 13157.7734 - 335ms/epoch - 2ms/step
Epoch 21/100
185/185 - 0s - loss: 13787.6562 - mae: 83.6059 - mse: 13787.6562 - val_loss: 12995.8242 - val_mae: 82.7723 - val_mse: 12995.8242 - 319ms/epoch - 2ms/step
Epoch 22/100
185/185 - 0s - loss: 13591.6738 - mae: 83.0275 - mse: 13591.6738 - val_loss: 12874.9609 - val_mae: 82.5706 - val_mse: 12874.9609 - 322ms/epoch - 2ms/step
Epoch 23/100
185/185 - 0s - loss: 13386.7402 - mae: 82.5338 - mse: 13386.7402 - val_loss: 12611.7266 - val_mae: 81.9839 - val_mse: 12611.7266 - 308ms/epoch - 2ms/step
Epoch 24/100
185/185 - 0s - loss: 13207.0938 - mae: 82.1043 - mse: 13207.0938 - val_loss: 12413.2637 - val_mae: 81.2319 - val_mse: 12413.2637 - 310ms/epoch - 2ms/step
Epoch 25/100
185/185 - 0s - loss: 13087.9023 - mae: 81.6433 - mse: 13087.9023 - val_loss: 12294.4658 - val_mae: 80.5416 - val_mse: 12294.4658 - 296ms/epoch - 2ms/step
Epoch 26/100
185/185 - 0s - loss: 12871.1953 - mae: 80.9402 - mse: 12871.1953 - val_loss: 12340.8730 - val_mae: 80.5203 - val_mse: 12340.8730 - 293ms/epoch - 2ms/step
Epoch 27/100
185/185 - 0s - loss: 12717.1943 - mae: 80.3571 - mse: 12717.1943 - val_loss: 12208.5098 - val_mae: 80.7847 - val_mse: 12208.5098 - 303ms/epoch - 2ms/step
Epoch 28/100
185/185 - 0s - loss: 12587.2559 - mae: 80.3127 - mse: 12587.2559 - val_loss: 11920.4639 - val_mae: 78.6437 - val_mse: 11920.4639 - 300ms/epoch - 2ms/step
Epoch 29/100
185/185 - 0s - loss: 12423.1396 - mae: 79.5204 - mse: 12423.1396 - val_loss: 11885.3525 - val_mae: 78.6584 - val_mse: 11885.3525 - 300ms/epoch - 2ms/step
Epoch 30/100
185/185 - 0s - loss: 12305.7256 - mae: 79.2714 - mse: 12305.7256 - val_loss: 11805.8975 - val_mae: 79.2682 - val_mse: 11805.8975 - 284ms/epoch - 2ms/step
Epoch 31/100
185/185 - 0s - loss: 12182.8740 - mae: 78.8812 - mse: 12182.8740 - val_loss: 11591.2031 - val_mae: 78.5081 - val_mse: 11591.2031 - 290ms/epoch - 2ms/step
Epoch 32/100
185/185 - 0s - loss: 12081.0654 - mae: 78.6414 - mse: 12081.0654 - val_loss: 11604.4180 - val_mae: 77.5868 - val_mse: 11604.4180 - 305ms/epoch - 2ms/step
Epoch 33/100
185/185 - 0s - loss: 11965.2891 - mae: 78.3869 - mse: 11965.2891 - val_loss: 11605.9707 - val_mae: 78.5173 - val_mse: 11605.9707 - 285ms/epoch - 2ms/step
Epoch 34/100
185/185 - 0s - loss: 11909.7490 - mae: 78.2501 - mse: 11909.7490 - val_loss: 11396.6416 - val_mae: 77.5606 - val_mse: 11396.6416 - 296ms/epoch - 2ms/step
Epoch 35/100
185/185 - 0s - loss: 11819.5166 - mae: 77.9391 - mse: 11819.5166 - val_loss: 11304.8018 - val_mae: 76.7827 - val_mse: 11304.8018 - 306ms/epoch - 2ms/step
Epoch 36/100
185/185 - 0s - loss: 11739.2070 - mae: 77.6167 - mse: 11739.2070 - val_loss: 11271.9141 - val_mae: 76.5335 - val_mse: 11271.9141 - 299ms/epoch - 2ms/step
Epoch 37/100
185/185 - 0s - loss: 11684.6162 - mae: 77.3851 - mse: 11684.6162 - val_loss: 11205.2031 - val_mae: 76.5000 - val_mse: 11205.2031 - 294ms/epoch - 2ms/step
Epoch 38/100
185/185 - 0s - loss: 11590.2939 - mae: 77.3153 - mse: 11590.2939 - val_loss: 11210.8398 - val_mae: 77.3778 - val_mse: 11210.8398 - 293ms/epoch - 2ms/step
Epoch 39/100
185/185 - 0s - loss: 11554.6543 - mae: 77.3344 - mse: 11554.6543 - val_loss: 11186.2021 - val_mae: 77.3039 - val_mse: 11186.2021 - 296ms/epoch - 2ms/step
Epoch 40/100
185/185 - 0s - loss: 11499.5664 - mae: 76.8795 - mse: 11499.5664 - val_loss: 11114.2988 - val_mae: 77.0794 - val_mse: 11114.2988 - 284ms/epoch - 2ms/step
Epoch 41/100
185/185 - 0s - loss: 11403.6006 - mae: 76.8356 - mse: 11403.6006 - val_loss: 10968.9668 - val_mae: 76.1248 - val_mse: 10968.9668 - 291ms/epoch - 2ms/step
Epoch 42/100
185/185 - 0s - loss: 11357.5205 - mae: 76.4621 - mse: 11357.5205 - val_loss: 10995.4443 - val_mae: 76.6958 - val_mse: 10995.4443 - 292ms/epoch - 2ms/step
Epoch 43/100
185/185 - 0s - loss: 11333.5537 - mae: 76.4347 - mse: 11333.5537 - val_loss: 10939.6641 - val_mae: 76.0316 - val_mse: 10939.6641 - 308ms/epoch - 2ms/step
Epoch 44/100
185/185 - 0s - loss: 11237.4209 - mae: 76.1863 - mse: 11237.4209 - val_loss: 10884.2314 - val_mae: 75.3913 - val_mse: 10884.2314 - 293ms/epoch - 2ms/step
Epoch 45/100
185/185 - 0s - loss: 11191.2588 - mae: 75.9601 - mse: 11191.2588 - val_loss: 10876.2520 - val_mae: 75.7183 - val_mse: 10876.2520 - 294ms/epoch - 2ms/step
Epoch 46/100
185/185 - 0s - loss: 11121.4863 - mae: 75.6905 - mse: 11121.4863 - val_loss: 10915.3828 - val_mae: 76.1956 - val_mse: 10915.3828 - 300ms/epoch - 2ms/step
Epoch 47/100
185/185 - 0s - loss: 11102.9521 - mae: 75.7018 - mse: 11102.9521 - val_loss: 10788.0020 - val_mae: 75.5672 - val_mse: 10788.0020 - 284ms/epoch - 2ms/step
Epoch 48/100
185/185 - 0s - loss: 11052.7100 - mae: 75.3654 - mse: 11052.7100 - val_loss: 10765.5127 - val_mae: 74.7146 - val_mse: 10765.5127 - 292ms/epoch - 2ms/step
Epoch 49/100
185/185 - 0s - loss: 10955.3652 - mae: 75.3401 - mse: 10955.3652 - val_loss: 10703.8516 - val_mae: 75.2360 - val_mse: 10703.8516 - 299ms/epoch - 2ms/step
Epoch 50/100
185/185 - 0s - loss: 10909.8926 - mae: 75.0886 - mse: 10909.8926 - val_loss: 10726.4775 - val_mae: 74.3854 - val_mse: 10726.4775 - 293ms/epoch - 2ms/step
Epoch 51/100
185/185 - 0s - loss: 10884.8750 - mae: 74.7792 - mse: 10884.8750 - val_loss: 10706.3525 - val_mae: 74.3684 - val_mse: 10706.3525 - 322ms/epoch - 2ms/step
Epoch 52/100
185/185 - 0s - loss: 10825.0781 - mae: 74.7050 - mse: 10825.0781 - val_loss: 10732.2412 - val_mae: 75.7907 - val_mse: 10732.2412 - 294ms/epoch - 2ms/step
Epoch 53/100
185/185 - 0s - loss: 10791.6846 - mae: 74.6670 - mse: 10791.6846 - val_loss: 10694.3330 - val_mae: 74.4633 - val_mse: 10694.3330 - 297ms/epoch - 2ms/step
Epoch 54/100
185/185 - 0s - loss: 10739.9727 - mae: 74.3655 - mse: 10739.9727 - val_loss: 10710.5664 - val_mae: 75.2861 - val_mse: 10710.5664 - 307ms/epoch - 2ms/step
Epoch 55/100
185/185 - 0s - loss: 10718.5088 - mae: 74.5362 - mse: 10718.5088 - val_loss: 10636.4980 - val_mae: 74.4041 - val_mse: 10636.4980 - 294ms/epoch - 2ms/step
Epoch 56/100
185/185 - 0s - loss: 10662.6582 - mae: 74.0365 - mse: 10662.6582 - val_loss: 10604.9746 - val_mae: 74.4748 - val_mse: 10604.9746 - 295ms/epoch - 2ms/step
Epoch 57/100
185/185 - 0s - loss: 10619.4121 - mae: 74.0625 - mse: 10619.4121 - val_loss: 10574.1602 - val_mae: 74.1478 - val_mse: 10574.1602 - 373ms/epoch - 2ms/step
Epoch 58/100
185/185 - 1s - loss: 10560.0605 - mae: 73.7207 - mse: 10560.0605 - val_loss: 10596.9199 - val_mae: 73.7088 - val_mse: 10596.9199 - 544ms/epoch - 3ms/step
Epoch 59/100
185/185 - 0s - loss: 10542.6201 - mae: 73.6809 - mse: 10542.6201 - val_loss: 10488.7275 - val_mae: 74.2828 - val_mse: 10488.7275 - 293ms/epoch - 2ms/step
Epoch 60/100
185/185 - 0s - loss: 10531.4189 - mae: 73.6933 - mse: 10531.4189 - val_loss: 10459.2119 - val_mae: 73.9506 - val_mse: 10459.2119 - 468ms/epoch - 3ms/step
Epoch 61/100
185/185 - 0s - loss: 10470.1670 - mae: 73.3439 - mse: 10470.1670 - val_loss: 10414.7070 - val_mae: 73.6118 - val_mse: 10414.7070 - 431ms/epoch - 2ms/step
Epoch 62/100
185/185 - 0s - loss: 10469.0459 - mae: 73.4878 - mse: 10469.0459 - val_loss: 10452.8721 - val_mae: 73.4297 - val_mse: 10452.8721 - 369ms/epoch - 2ms/step
Epoch 63/100
185/185 - 0s - loss: 10397.3008 - mae: 73.3151 - mse: 10397.3008 - val_loss: 10419.6680 - val_mae: 73.8382 - val_mse: 10419.6680 - 460ms/epoch - 2ms/step
Epoch 64/100
185/185 - 0s - loss: 10384.3721 - mae: 73.0374 - mse: 10384.3721 - val_loss: 10415.8115 - val_mae: 73.4050 - val_mse: 10415.8115 - 342ms/epoch - 2ms/step
Epoch 65/100
185/185 - 0s - loss: 10337.2959 - mae: 72.8732 - mse: 10337.2959 - val_loss: 10380.3486 - val_mae: 73.8491 - val_mse: 10380.3486 - 336ms/epoch - 2ms/step
Epoch 66/100
185/185 - 0s - loss: 10311.8115 - mae: 72.9647 - mse: 10311.8115 - val_loss: 10381.5342 - val_mae: 73.8620 - val_mse: 10381.5342 - 342ms/epoch - 2ms/step
Epoch 67/100
185/185 - 0s - loss: 10261.8086 - mae: 72.7111 - mse: 10261.8086 - val_loss: 10338.1348 - val_mae: 73.3212 - val_mse: 10338.1348 - 353ms/epoch - 2ms/step
Epoch 68/100
185/185 - 0s - loss: 10279.1182 - mae: 72.9053 - mse: 10279.1182 - val_loss: 10350.2812 - val_mae: 73.7129 - val_mse: 10350.2812 - 313ms/epoch - 2ms/step
Epoch 69/100
185/185 - 0s - loss: 10235.5088 - mae: 72.6956 - mse: 10235.5088 - val_loss: 10453.0146 - val_mae: 73.9359 - val_mse: 10453.0146 - 333ms/epoch - 2ms/step
Epoch 70/100
185/185 - 0s - loss: 10204.2871 - mae: 72.6185 - mse: 10204.2871 - val_loss: 10387.7402 - val_mae: 74.2556 - val_mse: 10387.7402 - 317ms/epoch - 2ms/step
Epoch 71/100
185/185 - 0s - loss: 10191.3682 - mae: 72.7063 - mse: 10191.3682 - val_loss: 10286.3193 - val_mae: 73.0755 - val_mse: 10286.3193 - 310ms/epoch - 2ms/step
Epoch 72/100
185/185 - 0s - loss: 10131.9346 - mae: 72.5225 - mse: 10131.9346 - val_loss: 10391.8867 - val_mae: 74.0605 - val_mse: 10391.8867 - 361ms/epoch - 2ms/step
Epoch 73/100
185/185 - 0s - loss: 10149.1191 - mae: 72.5335 - mse: 10149.1191 - val_loss: 10243.7217 - val_mae: 73.0670 - val_mse: 10243.7217 - 330ms/epoch - 2ms/step
Epoch 74/100
185/185 - 0s - loss: 10122.2979 - mae: 72.4067 - mse: 10122.2979 - val_loss: 10299.7559 - val_mae: 73.2957 - val_mse: 10299.7559 - 316ms/epoch - 2ms/step
Epoch 75/100
185/185 - 0s - loss: 10066.7637 - mae: 72.2932 - mse: 10066.7637 - val_loss: 10325.8867 - val_mae: 73.6267 - val_mse: 10325.8867 - 319ms/epoch - 2ms/step
Epoch 76/100
185/185 - 0s - loss: 10071.0635 - mae: 72.1828 - mse: 10071.0635 - val_loss: 10430.4785 - val_mae: 74.4775 - val_mse: 10430.4785 - 357ms/epoch - 2ms/step
Epoch 77/100
185/185 - 0s - loss: 10047.2041 - mae: 72.1519 - mse: 10047.2041 - val_loss: 10295.0244 - val_mae: 73.8294 - val_mse: 10295.0244 - 363ms/epoch - 2ms/step
Epoch 78/100
185/185 - 0s - loss: 10031.2334 - mae: 72.2399 - mse: 10031.2334 - val_loss: 10215.3037 - val_mae: 73.1533 - val_mse: 10215.3037 - 416ms/epoch - 2ms/step
Epoch 79/100
185/185 - 0s - loss: 10033.2148 - mae: 72.1852 - mse: 10033.2148 - val_loss: 10258.9170 - val_mae: 73.3910 - val_mse: 10258.9170 - 335ms/epoch - 2ms/step
Epoch 80/100
185/185 - 0s - loss: 9992.4873 - mae: 71.9799 - mse: 9992.4873 - val_loss: 10356.4004 - val_mae: 73.7183 - val_mse: 10356.4004 - 341ms/epoch - 2ms/step
Epoch 81/100
185/185 - 0s - loss: 9986.9941 - mae: 71.9810 - mse: 9986.9941 - val_loss: 10249.9941 - val_mae: 72.6778 - val_mse: 10249.9941 - 324ms/epoch - 2ms/step
Epoch 82/100
185/185 - 0s - loss: 9961.0947 - mae: 72.0211 - mse: 9961.0947 - val_loss: 10297.2646 - val_mae: 73.6707 - val_mse: 10297.2646 - 335ms/epoch - 2ms/step
Epoch 83/100
185/185 - 0s - loss: 9925.8711 - mae: 71.9800 - mse: 9925.8711 - val_loss: 10312.6172 - val_mae: 73.9291 - val_mse: 10312.6172 - 318ms/epoch - 2ms/step
Epoch 84/100
185/185 - 0s - loss: 9936.9775 - mae: 71.8505 - mse: 9936.9775 - val_loss: 10195.7520 - val_mae: 73.0342 - val_mse: 10195.7520 - 453ms/epoch - 2ms/step
Epoch 85/100
185/185 - 0s - loss: 9907.0527 - mae: 71.7890 - mse: 9907.0527 - val_loss: 10236.0322 - val_mae: 73.3706 - val_mse: 10236.0322 - 329ms/epoch - 2ms/step
Epoch 86/100
185/185 - 0s - loss: 9885.1572 - mae: 71.7143 - mse: 9885.1572 - val_loss: 10216.9854 - val_mae: 73.4159 - val_mse: 10216.9854 - 332ms/epoch - 2ms/step
Epoch 87/100
185/185 - 0s - loss: 9912.1709 - mae: 71.7934 - mse: 9912.1709 - val_loss: 10167.8926 - val_mae: 73.0662 - val_mse: 10167.8926 - 391ms/epoch - 2ms/step
Epoch 88/100
185/185 - 0s - loss: 9865.7031 - mae: 71.7720 - mse: 9865.7031 - val_loss: 10259.5146 - val_mae: 73.3353 - val_mse: 10259.5146 - 356ms/epoch - 2ms/step
Epoch 89/100
185/185 - 0s - loss: 9878.9258 - mae: 71.7433 - mse: 9878.9258 - val_loss: 10266.4102 - val_mae: 73.6632 - val_mse: 10266.4102 - 334ms/epoch - 2ms/step
Epoch 90/100
185/185 - 0s - loss: 9857.1768 - mae: 71.6709 - mse: 9857.1768 - val_loss: 10156.8115 - val_mae: 72.7731 - val_mse: 10156.8115 - 334ms/epoch - 2ms/step
Epoch 91/100
185/185 - 0s - loss: 9834.6973 - mae: 71.5519 - mse: 9834.6973 - val_loss: 10152.1133 - val_mae: 73.2450 - val_mse: 10152.1133 - 326ms/epoch - 2ms/step
Epoch 92/100
185/185 - 0s - loss: 9826.6895 - mae: 71.6471 - mse: 9826.6895 - val_loss: 10257.6348 - val_mae: 73.6685 - val_mse: 10257.6348 - 322ms/epoch - 2ms/step
Epoch 93/100
185/185 - 0s - loss: 9826.1230 - mae: 71.5252 - mse: 9826.1230 - val_loss: 10114.4326 - val_mae: 72.9471 - val_mse: 10114.4326 - 358ms/epoch - 2ms/step
Epoch 94/100
185/185 - 0s - loss: 9816.6787 - mae: 71.7350 - mse: 9816.6787 - val_loss: 10170.5625 - val_mae: 73.1548 - val_mse: 10170.5625 - 325ms/epoch - 2ms/step
Epoch 95/100
185/185 - 0s - loss: 9803.4336 - mae: 71.5177 - mse: 9803.4336 - val_loss: 10206.5225 - val_mae: 73.5780 - val_mse: 10206.5225 - 385ms/epoch - 2ms/step
Epoch 96/100
185/185 - 0s - loss: 9769.1299 - mae: 71.5661 - mse: 9769.1299 - val_loss: 10167.6416 - val_mae: 72.9961 - val_mse: 10167.6416 - 397ms/epoch - 2ms/step
Epoch 97/100
185/185 - 0s - loss: 9790.6025 - mae: 71.6272 - mse: 9790.6025 - val_loss: 10110.7432 - val_mae: 72.3962 - val_mse: 10110.7432 - 323ms/epoch - 2ms/step
Epoch 98/100
185/185 - 0s - loss: 9785.9639 - mae: 71.5982 - mse: 9785.9639 - val_loss: 10155.6797 - val_mae: 72.8482 - val_mse: 10155.6797 - 326ms/epoch - 2ms/step
Epoch 99/100
185/185 - 0s - loss: 9773.7324 - mae: 71.6151 - mse: 9773.7324 - val_loss: 10116.4189 - val_mae: 72.4858 - val_mse: 10116.4189 - 366ms/epoch - 2ms/step
Epoch 100/100
185/185 - 0s - loss: 9744.9854 - mae: 71.3753 - mse: 9744.9854 - val_loss: 10144.1875 - val_mae: 73.3299 - val_mse: 10144.1875 - 398ms/epoch - 2ms/step
26/26 [==============================] - 0s 2ms/step
MSE: 8880.13
MAE: 66.26
r2 score: 0.63

# *Finding: RF regression model has the best performance.

### 1. predict price 3 years later, and calculate the growth rate

In [8]:
# select needed features for prediction of 2026 rental price
data_2026 = pd.read_csv("../data/curated/final_data/merged_data_2026.csv")
data_2026_test = data_2026[features_list]
data_2026_test

,personal_income,pop_density,offence_count,log_school_distance,log_station_distance,log_hospital_distance,log_mall_distance,log_park_distance,log_CBD_distance,num_bedroom,num_bathroom
0,79514.553071,2814.014080,23.132872,0.640804,2.475412,1.906040,1.239505,1.345502,4.578730,4,2
1,79514.553071,4306.277854,23.132872,-0.348952,1.681479,1.438925,1.052926,1.716843,4.559835,4,2
2,79514.553071,2814.014080,23.132872,0.095820,2.187960,1.847653,1.673884,1.622239,4.586220,2,2
3,79514.553071,2814.014080,23.132872,-0.393160,2.092679,1.736704,0.793410,1.183953,4.578058,4,2
4,75319.429183,184.687628,34.708923,0.799813,2.315778,2.017863,1.375422,0.115940,4.602687,4,2
...,...,...,...,...,...,...,...,...,...,...,...
8214,112895.360426,1832.451409,25.631382,-2.228826,0.138021,0.374363,0.344505,1.026702,3.826546,2,1
8215,112895.360426,1832.451409,25.631382,-1.427862,0.754430,1.122437,0.873918,1.320736,3.823240,4,3
8216,112895.360426,1832.451409,25.631382,-0.199202,1.034856,1.025788,0.821525,1.484705,3.805227,3,1
8217,112895.360426,1832.451409,25.631382,-1.237029,0.614537,0.623725,0.746158,1.316399,3.810149,1,1
8218,112895.360426,1832.451409,25.631382,-1.168365,0.425986,0.910821,0.909697,1.072542,3.831748,1,1

In [9]:
# predict the 2026 rental price by RF
pred_2026 = final_rf_model.predict(data_2026_test)
pred_2026

array([636.01378307, 626.71496032, 566.54353415, ..., 578.28616643,
       351.03117401, 409.6981394 ])

In [10]:
# save the prediction as a new row of data, and record its 2023 price
data_2023 = pd.read_csv("../data/curated/final_data/merged_data_2023.csv") 
data_2026['rental_price_2023'] = data_2023['rental_price']
data_2026['predicted_price_2026'] = pred_2026
data_2026

,name,coordinates,sa2_code,sa2_name,sa2_geometry,num_bedroom,num_bathroom,num_parking,pop_density,personal_income,offence_count,log_school_distance,log_hospital_distance,log_mall_distance,log_park_distance,log_station_distance,log_CBD_distance,rental_price_2023,predicted_price_2026
0,31 Chittagong Drive Clyde North VIC 3978,"[-38.1053122, 145.3570863]",212031556.0,Clyde North - South,POLYGON ((145.37034567475234 -38.0937851973191...,4,2,2.0,2814.014080,79514.553071,23.132872,0.640804,1.906040,1.239505,1.345502,2.475412,4.578730,575.0,636.013783
1,50 Elmtree Crescent Clyde North VIC 3978,"[-38.0825712, 145.3561984]",212031555.0,Clyde North - North,POLYGON ((145.3346630127421 -38.07820964472685...,4,2,2.0,4306.277854,79514.553071,23.132872,-0.348952,1.438925,1.052926,1.716843,1.681479,4.559835,560.0,626.714960
2,7 Mortdale Lane Clyde North VIC 3978,"[-38.0961758, 145.3800644]",212031556.0,Clyde North - South,POLYGON ((145.37034567475234 -38.0937851973191...,2,2,1.0,2814.014080,79514.553071,23.132872,0.095820,1.847653,1.673884,1.622239,2.187960,4.586220,490.0,566.543534
3,54 Walhallow Drive Clyde North VIC 3978,"[-38.1133324, 145.3457396]",212031556.0,Clyde North - South,POLYGON ((145.37034567475234 -38.0937851973191...,4,2,1.0,2814.014080,79514.553071,23.132872,-0.393160,1.736704,0.793410,1.183953,2.092679,4.578058,540.0,586.459791
4,10 Sicily Road Clyde North VIC 3978,"[-38.1295789, 145.3642993]",212031303.0,Cranbourne South,POLYGON ((145.3254642788471 -38.12742071438774...,4,2,2.0,184.687628,75319.429183,34.708923,0.799813,2.017863,1.375422,0.115940,2.315778,4.602687,520.0,593.995740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8214,61 Tongue Street Yarraville VIC 3013,"[-37.8131463, 144.8909053]",213031352.0,Yarraville,POLYGON ((144.85914995429522 -37.8176431203511...,2,1,0.0,1832.451409,112895.360426,25.631382,-2.228826,0.374363,0.344505,1.026702,0.138021,3.826546,630.0,613.106051
8215,47 Mill Avenue Yarraville VIC 3013,"[-37.8222822, 144.872198]",213031352.0,Yarraville,POLYGON ((144.85914995429522 -37.8176431203511...,4,3,2.0,1832.451409,112895.360426,25.631382,-1.427862,1.122437,0.873918,1.320736,0.754430,3.823240,730.0,781.694406
8216,12 Adeney Street Yarraville VIC 3013,"[-37.8163817, 144.8666543]",213031352.0,Yarraville,POLYGON ((144.85914995429522 -37.8176431203511...,3,1,2.0,1832.451409,112895.360426,25.631382,-0.199202,1.025788,0.821525,1.484705,1.034856,3.805227,450.0,578.286166
8217,229B Somerville Road Yarraville VIC 3013,"[-37.8124289, 144.8779569]",213031352.0,Yarraville,POLYGON ((144.85914995429522 -37.8176431203511...,1,1,0.0,1832.451409,112895.360426,25.631382,-1.237029,0.623725,0.746158,1.316399,0.614537,3.810149,300.0,351.031174
8218,4/185 Francis Street Yarraville VIC 3013,"[-37.8206224, 144.8827922]",213031352.0,Yarraville,POLYGON ((144.85914995429522 -37.8176431203511...,1,1,2.0,1832.451409,112895.360426,25.631382,-1.168365,0.910821,0.909697,1.072542,0.425986,3.831748,420.0,409.698139

In [11]:
# calculate rental price growth_rate(%) for properties(2023~2026)
data_2026['growth_rate(%)'] = ((data_2026['predicted_price_2026'] - data_2026['rental_price_2023']) / data_2026['rental_price_2023']) * 100
data_2026

,name,coordinates,sa2_code,sa2_name,sa2_geometry,num_bedroom,num_bathroom,num_parking,pop_density,personal_income,offence_count,log_school_distance,log_hospital_distance,log_mall_distance,log_park_distance,log_station_distance,log_CBD_distance,rental_price_2023,predicted_price_2026,growth_rate(%)
0,31 Chittagong Drive Clyde North VIC 3978,"[-38.1053122, 145.3570863]",212031556.0,Clyde North - South,POLYGON ((145.37034567475234 -38.0937851973191...,4,2,2.0,2814.014080,79514.553071,23.132872,0.640804,1.906040,1.239505,1.345502,2.475412,4.578730,575.0,636.013783,10.611093
1,50 Elmtree Crescent Clyde North VIC 3978,"[-38.0825712, 145.3561984]",212031555.0,Clyde North - North,POLYGON ((145.3346630127421 -38.07820964472685...,4,2,2.0,4306.277854,79514.553071,23.132872,-0.348952,1.438925,1.052926,1.716843,1.681479,4.559835,560.0,626.714960,11.913386
2,7 Mortdale Lane Clyde North VIC 3978,"[-38.0961758, 145.3800644]",212031556.0,Clyde North - South,POLYGON ((145.37034567475234 -38.0937851973191...,2,2,1.0,2814.014080,79514.553071,23.132872,0.095820,1.847653,1.673884,1.622239,2.187960,4.586220,490.0,566.543534,15.621129
3,54 Walhallow Drive Clyde North VIC 3978,"[-38.1133324, 145.3457396]",212031556.0,Clyde North - South,POLYGON ((145.37034567475234 -38.0937851973191...,4,2,1.0,2814.014080,79514.553071,23.132872,-0.393160,1.736704,0.793410,1.183953,2.092679,4.578058,540.0,586.459791,8.603665
4,10 Sicily Road Clyde North VIC 3978,"[-38.1295789, 145.3642993]",212031303.0,Cranbourne South,POLYGON ((145.3254642788471 -38.12742071438774...,4,2,2.0,184.687628,75319.429183,34.708923,0.799813,2.017863,1.375422,0.115940,2.315778,4.602687,520.0,593.995740,14.229950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8214,61 Tongue Street Yarraville VIC 3013,"[-37.8131463, 144.8909053]",213031352.0,Yarraville,POLYGON ((144.85914995429522 -37.8176431203511...,2,1,0.0,1832.451409,112895.360426,25.631382,-2.228826,0.374363,0.344505,1.026702,0.138021,3.826546,630.0,613.106051,-2.681579
8215,47 Mill Avenue Yarraville VIC 3013,"[-37.8222822, 144.872198]",213031352.0,Yarraville,POLYGON ((144.85914995429522 -37.8176431203511...,4,3,2.0,1832.451409,112895.360426,25.631382,-1.427862,1.122437,0.873918,1.320736,0.754430,3.823240,730.0,781.694406,7.081425
8216,12 Adeney Street Yarraville VIC 3013,"[-37.8163817, 144.8666543]",213031352.0,Yarraville,POLYGON ((144.85914995429522 -37.8176431203511...,3,1,2.0,1832.451409,112895.360426,25.631382,-0.199202,1.025788,0.821525,1.484705,1.034856,3.805227,450.0,578.286166,28.508037
8217,229B Somerville Road Yarraville VIC 3013,"[-37.8124289, 144.8779569]",213031352.0,Yarraville,POLYGON ((144.85914995429522 -37.8176431203511...,1,1,0.0,1832.451409,112895.360426,25.631382,-1.237029,0.623725,0.746158,1.316399,0.614537,3.810149,300.0,351.031174,17.010391
8218,4/185 Francis Street Yarraville VIC 3013,"[-37.8206224, 144.8827922]",213031352.0,Yarraville,POLYGON ((144.85914995429522 -37.8176431203511...,1,1,2.0,1832.451409,112895.360426,25.631382,-1.168365,0.910821,0.909697,1.072542,0.425986,3.831748,420.0,409.698139,-2.452824

### 2. save the prediction results as a CSV file

In [12]:
path = '../data/curated/final_data/predicted_data_2026.csv'
data_2026.to_csv(path, index=False)
data_2026 = pd.read_csv("../data/curated/final_data/predicted_data_2026.csv") 
data_2026

,name,coordinates,sa2_code,sa2_name,sa2_geometry,num_bedroom,num_bathroom,num_parking,pop_density,personal_income,offence_count,log_school_distance,log_hospital_distance,log_mall_distance,log_park_distance,log_station_distance,log_CBD_distance,rental_price_2023,predicted_price_2026,growth_rate(%)
0,31 Chittagong Drive Clyde North VIC 3978,"[-38.1053122, 145.3570863]",212031556.0,Clyde North - South,POLYGON ((145.37034567475234 -38.0937851973191...,4,2,2.0,2814.014080,79514.553071,23.132872,0.640804,1.906040,1.239505,1.345502,2.475412,4.578730,575.0,636.013783,10.611093
1,50 Elmtree Crescent Clyde North VIC 3978,"[-38.0825712, 145.3561984]",212031555.0,Clyde North - North,POLYGON ((145.3346630127421 -38.07820964472685...,4,2,2.0,4306.277854,79514.553071,23.132872,-0.348952,1.438925,1.052926,1.716843,1.681479,4.559835,560.0,626.714960,11.913386
2,7 Mortdale Lane Clyde North VIC 3978,"[-38.0961758, 145.3800644]",212031556.0,Clyde North - South,POLYGON ((145.37034567475234 -38.0937851973191...,2,2,1.0,2814.014080,79514.553071,23.132872,0.095820,1.847653,1.673884,1.622239,2.187960,4.586220,490.0,566.543534,15.621129
3,54 Walhallow Drive Clyde North VIC 3978,"[-38.1133324, 145.3457396]",212031556.0,Clyde North - South,POLYGON ((145.37034567475234 -38.0937851973191...,4,2,1.0,2814.014080,79514.553071,23.132872,-0.393160,1.736704,0.793410,1.183953,2.092679,4.578058,540.0,586.459791,8.603665
4,10 Sicily Road Clyde North VIC 3978,"[-38.1295789, 145.3642993]",212031303.0,Cranbourne South,POLYGON ((145.3254642788471 -38.12742071438774...,4,2,2.0,184.687628,75319.429183,34.708923,0.799813,2.017863,1.375422,0.115940,2.315778,4.602687,520.0,593.995740,14.229950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8214,61 Tongue Street Yarraville VIC 3013,"[-37.8131463, 144.8909053]",213031352.0,Yarraville,POLYGON ((144.85914995429522 -37.8176431203511...,2,1,0.0,1832.451409,112895.360426,25.631382,-2.228826,0.374363,0.344505,1.026702,0.138021,3.826546,630.0,613.106051,-2.681579
8215,47 Mill Avenue Yarraville VIC 3013,"[-37.8222822, 144.872198]",213031352.0,Yarraville,POLYGON ((144.85914995429522 -37.8176431203511...,4,3,2.0,1832.451409,112895.360426,25.631382,-1.427862,1.122437,0.873918,1.320736,0.754430,3.823240,730.0,781.694406,7.081425
8216,12 Adeney Street Yarraville VIC 3013,"[-37.8163817, 144.8666543]",213031352.0,Yarraville,POLYGON ((144.85914995429522 -37.8176431203511...,3,1,2.0,1832.451409,112895.360426,25.631382,-0.199202,1.025788,0.821525,1.484705,1.034856,3.805227,450.0,578.286166,28.508037
8217,229B Somerville Road Yarraville VIC 3013,"[-37.8124289, 144.8779569]",213031352.0,Yarraville,POLYGON ((144.85914995429522 -37.8176431203511...,1,1,0.0,1832.451409,112895.360426,25.631382,-1.237029,0.623725,0.746158,1.316399,0.614537,3.810149,300.0,351.031174,17.010391
8218,4/185 Francis Street Yarraville VIC 3013,"[-37.8206224, 144.8827922]",213031352.0,Yarraville,POLYGON ((144.85914995429522 -37.8176431203511...,1,1,2.0,1832.451409,112895.360426,25.631382,-1.168365,0.910821,0.909697,1.072542,0.425986,3.831748,420.0,409.698139,-2.452824

In [13]:
# calculate average growth_rate(%) for each sa2_name
average_growth_rate_by_sa2 = data_2026.groupby('sa2_name')['growth_rate(%)'].mean().reset_index()
print(average_growth_rate_by_sa2)

                       sa2_name  growth_rate(%)
0                    Abbotsford        4.902311
1                  Airport West        4.133877
2                   Albert Park        0.855093
3                     Alfredton       20.628217
4        Alphington - Fairfield        7.634165
..                          ...             ...
350       Wonthaggi - Inverloch        7.155537
351        Wyndham Vale - North       17.468025
352        Wyndham Vale - South       22.369693
353  Yallourn North - Glengarry        0.787844
354                  Yarraville        3.959479

[355 rows x 2 columns]

In [14]:
# sort the average growth rate for rental price, and find the top 10 sa2 areas with highest value
sorted_growth_rates = average_growth_rate_by_sa2.sort_values(by='growth_rate(%)', ascending=False)
top_10_sa2 = sorted_growth_rates.head(10)
print(top_10_sa2)

                   sa2_name  growth_rate(%)
218              Myrtleford      242.936746
111          Doreen - North       42.450243
112          Doreen - South       37.311957
254      Point Cook - South       34.572889
208        Moe - Newborough       30.490874
279                Seabrook       26.918311
265  Reservoir - North West       26.094571
52         Bundoora - North       25.993778
162                Hillside       24.434810
157    Heidelberg - Rosanna       24.191940